apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Values.microservices.studentService.serviceName}}'
  labels:
    app: '{{.Values.microservices.studentService.serviceName}}'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: '{{.Values.microservices.studentService.serviceName}}'
  template:
    metadata:
      labels:
        app: '{{.Values.microservices.studentService.serviceName}}'
    spec:
      containers:
      - name: '{{.Values.microservices.studentService.serviceName}}'
        image: '{{.Values.microservices.studentService.dockerImage}}'
        ports:
        - containerPort: 8080
        env:
        - name: '{{.Values.microservices.studentService.envs.MYSQL_ROOT_PASSWORD.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.studentService.serviceName}}'
              key: '{{.Values.microservices.studentService.envs.MYSQL_ROOT_PASSWORD.name}}'
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: '{{.Values.microservices.studentService.maxCPU}}'
            memory: '{{.Values.microservices.studentService.maxMemory}}'
